[project]
name = "pz-manager"
version = "0.0.1"
dependencies = [
    "requests",
    "fastapi",
    "typing",
    "pydantic",
    "python-dotenv",
    "uvicorn",
    'importlib-metadata; python_version<"3.10"',
]
[project.scripts]
pz_web = "pz-manager.main"