[project]
name = "ezpz4u"
version = "0.0.1"
dependencies = [
    "requests",
    "fastapi",
    "typing",
    "pydantic",
    "python-dotenv",
    "uvicorn",
    'importlib-metadata; python_version<"3.10"',
]
[project.scripts]
ezpz4u = "ezpz.main:start_server"